FROM python:3.10-slim

WORKDIR /app

COPY monitoring /app
COPY IMDB_Dataset.csv /app
COPY requirements_streamlit.txt .

RUN pip install --no-cache-dir -r requirements_streamlit.txt

EXPOSE 8501

CMD ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]


