# Dockerfile.fastapi
FROM python:3.10-slim

# Establishees a working directory.
WORKDIR /app

# Copies your application code & model.
COPY fastapi_app/ /app
COPY sentiment_model.pkl /app

# Copies and installs all FastAPI requirements.
COPY requirements_fastapi.txt /app/requirements_fastapi.txt
RUN pip install --no-cache-dir -r requirements_fastapi.txt

# Runs with log folder.
RUN mkdir -p /app/logs

# Port Uvicorn will run on.
EXPOSE 8000

# Launches Uvicorn.
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
